@startuml Hospedagem

entity pessoa{
    id <<PK>>
    telefone
    pais
    estado
    endereco
    cidade
    cep
}

entity pessoa_fisica{
    id <<PK>>
    nome
    cpf
    rg
    genero
    data_nascimento
    telefone_emergencia
    id_pessoa <<FK>>
}

entity pessoa_juridica{
    id <<PK>>
    cnpj
    razao_social
    nome_fantasia
    data_abertura
    id_pessoa <<FK>>
}

entity cargo{
    id <<PK>>
    nome
    salario
}

entity funcionario{
    id <<PK>>
    matricula
    data_admissao
    situacao
    id_cargo <<FK>>
    id_pessoa_fisica <<FK>>
}

entity reserva{
    id <<PK>>
    id_pessoa <<FK>>
    id_local_hospedagem <<FK>>
    data_inicio
    data_fim
    valor_total
}

entity hospedagem{
    id <<PK>>
    id_reserva <<FK>>
    id_comanda <<FK>>
    data_check_in
    data_check_out
}

entity pessoa_hospedagem{
    id_hospedagem <<FK>>
    id_pessoa <<FK>>
}

entity tipo_local_hospedagem{
    id <<PK>>
    nome
    descricao
    numero_de_camas
}

entity local_hospedagem{
    id <<PK>>
    id_tipo_local_hospedagem <<FK>>
    id_ quarto <<FK>>
    nome
    descricao
    endereco
}

entity tipo_quarto{
    id <<PK>>
    nome
    preco
    descricao
}

entity quarto{
    id <<PK>>
    id_tipo_quarto <<FK>>
    id_hospedagem <<FK>>
    capacidade
}

entity servico{
    id <<PK>>
    nome
    preco
    descricao
}

entity servico_funcionario_hospedagem{
    id_servico <<FK>>
    id_funcionario <<FK>>
    id_hospedagem <<FK>>
    data_inicio_servico
    data_fim_servico
    status_do_servico
}

entity produto{
    id <<PK>>
    id_local_hospedagem <<FK>>
    nome
    descricao
    preco
    quantidade_em_estoque
}

entity comanda_produto{
    id_comanda <<FK>>
    id_produto <<FK>>
    quantidade
    valor
}

entity comanda{
    id <<PK>>
    id_pessoa <<FK>>
    data_pagamento
    forma_pagamento
}

pessoa -- pessoa_fisica
pessoa -- pessoa_juridica

pessoa_fisica -- funcionario

funcionario -- cargo

reserva -- pessoa

hospedagem -- reserva

local_hospedagem -- tipo_local_hospedagem
local_hospedagem -- reserva

quarto -- tipo_quarto
quarto -- local_hospedagem

servico_funcionario_hospedagem -- servico
servico_funcionario_hospedagem -- funcionario
servico_funcionario_hospedagem -- hospedagem

produto -- local_hospedagem

comanda -- hospedagem

comanda_produto -- comanda
comanda_produto -- produto

pessoa_hospedagem -- hospedagem
pessoa_hospedagem -- pessoa_fisica

@enduml