insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (1, 2, 2, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '43533 Clyde Gallagher Avenue');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (2, 6, 4, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '95715 Mcbride Lane');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (3, 8, 5, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '8162 Elka Park');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (4, 8, 5, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '369 Roth Street');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (5, 3, 7, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '8078 Blue Bill Park Plaza');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (6, 7, 6, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '9840 Utah Point');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (7, 4, 1, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '781 Sutteridge Hill');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (8, 2, 2, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '38249 Hooker Road');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (9, 2, 3, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '0 Hoard Terrace');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (10, 1, 7, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '35 Del Mar Point');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (11, 7, 6, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '055 Westridge Avenue');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (12, 4, 4, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '712 Westridge Alley');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (13, 1, 8, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '9 Buena Vista Court');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (14, 2, 6, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '676 Fairview Road');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (15, 8, 5, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '07 Meadow Ridge Park');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (16, 6, 7, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '5 Trailsway Circle');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (17, 5, 2, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '68335 Beilfuss Avenue');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (18, 5, 4, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '60 Pawling Park');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (19, 2, 7, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '35 Dawn Place');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (20, 4, 3, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '9 Bartillon Avenue');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (21, 5, 8, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '65 Bashford Terrace');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (22, 1, 6, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '703 Stone Corner Avenue');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (23, 6, 8, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '3957 1st Avenue');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (24, 1, 4, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '31663 Loomis Court');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (25, 1, 8, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '69962 Bonner Trail');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (26, 8, 8, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '4 Spenser Circle');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (27, 4, 8, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '44 Jackson Way');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (28, 8, 4, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '15182 Stoughton Park');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (29, 7, 2, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '4 Sunnyside Pass');
insert into local_hospedagem (id, id_tipo_local_hospedagem, id_quarto, nome, descricao, endereço) values (30, 7, 4, 'Hotel', 'Um quarto aconchegante perfeito para uma família', '5 Ridgeview Drive');
